version: '3.8'

services:
  frontend:
    build:
      context: ./vue3
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    depends_on:
      - nginx

  backend:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend