version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: vue3/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend